### ISSUE TITLE
Question: Is generated code strong mode compliant?

### ISSUE THREAD

**Issue by alexeieleusis** [polux/adts#2] opened 2016-11-27 22:57 UTC

**Comment by polux** [comment] 2016-11-28 12:00
No it's not :) Can I mark #1 as a duplicate of this?

**Comment by polux** [comment] 2016-11-28 12:11
Oh sorry, I just realized this issue is about the generated code while #1 is about the generator itself. I'm not sure whether the generated code is strong mode compliant or not: it might be by accident, but I would guess it isn't. Did you give it a try?

**Comment by alexeieleusis** [comment] 2016-11-29 06:37
I haven't, I am still learning adts and was thinking about implementing some by hand when I came across this project. I thought about using it, but since the code I will use it needs to be strong mode compliant, I thought about asking. I will try at some point and update this thread.

**Comment by alexeieleusis** [comment] 2016-12-08 03:35
The answer is no, for the generated code in the example folder there is one warning and the generated code is not only not strong mode compliant but also incorrect, output below:

```dart
library lists;

_dynamicToJson(value) {
  if (value == null || value is num || value is int || value is double
      || value is bool || value is String) {
    return value;
  } else if (value is List) {
    return value.map(_dynamicToJson).toList();
  } else {
    return value.toJson();
  }
}
_nonExhaustive() {
  throw "non-exhaustive matching";
}

abstract class LinkedList<A> {
  bool get isNil => false;
  bool get isCons => false;
  Nil<A> get asNil => null;
  Cons<A> get asCons => null;
  Object accept(LinkedListVisitor<A, Object> visitor);
  Object match({Object nil(),
  Object cons(A head, LinkedList<A> tail),
  Object otherwise(): _nonExhaustive});
  Map toJson();
// INFO: This function declares a return type of 'LinkedList', but doesn't end with a return statement. ([adts] example/generated.dart:27)
  static LinkedList fromJson(Map json,
      aFromJson(Map json)) {
    LinkedList result;
    result = Nil.fromJson(json);
    if (result != null) return result;
    result = Cons.fromJson(json, aFromJson);
    if (result != null) return result;
  }
}

abstract class LinkedListVisitor<A, R> {
  R visitNil(Nil<A> nil);
  R visitCons(Cons<A> cons);
}

class Nil<A> extends LinkedList<A> {
  Nil();
  bool get isNil => true;
  Nil<A> get asNil => this;
  bool operator ==(other) {
    return identical(this, other)
        || (other is Nil<A>);
  }
  String toString() {
    return 'Nil()';
  }
  Object accept(LinkedListVisitor<A, Object> visitor) {
    return visitor.visitNil(this);
  }
  Object match({Object nil(),
  Object cons(A head, LinkedList<A> tail),
  Object otherwise(): _nonExhaustive}) {
    return (nil != null) ? nil() : otherwise();
  }
  Map toJson() {
    return { 'tag': 'Nil' };
  }
  static Nil fromJson(Map json) {
    if (json['tag'] != 'Nil') return null;
    return new Nil();
  }
  int get hashCode => 0;
}

class Cons<A> extends LinkedList<A> {
  final A head;
  final LinkedList<A> tail;
  final int hashCode;
  Cons(A head, LinkedList<A> tail)
      : this.head = head
  , this.tail = tail
  , this.hashCode = Cons._hashCode(head, tail);
  bool get isCons => true;
  Cons<A> get asCons => this;
  bool operator ==(other) {
    return identical(this, other)
        || (other is Cons<A>
            && head == other.head
            && tail == other.tail);
  }
  static int _hashCode(head, tail) {
    int result = "Cons".hashCode;
    result = 31 * result + head.hashCode;
    result = 31 * result + tail.hashCode;
    return result;
  }
  Object accept(LinkedListVisitor<A, Object> visitor) {
    return visitor.visitCons(this);
  }
  Object match({Object nil(),
  Object cons(A head, LinkedList<A> tail),
  Object otherwise(): _nonExhaustive}) {
    return (cons != null) ? cons(head, tail) : otherwise();
  }
  Cons<A> copy({A head, LinkedList<A> tail}) {
    return new Cons(
        (head != null) ? head : this.head,
        (tail != null) ? tail : this.tail);
  }
  Map toJson() {
    return { 'tag': 'Cons',
      'head': _dynamicToJson(head),
      'tail': tail.toJson() };
  }
  static Cons fromJson(Map json,
      aFromJson(Map json)) {
    if (json['tag'] != 'Cons') return null;
    return new Cons(aFromJson(json['head']),
        LinkedList.fromJson(json['tail'], aFromJson));
  }
  String toString() {
    return '$head::$tail';
  }
}
```

When I have time (which might not happen soon) I can fix this. Hopefully is not urgent.

**Comment by alexeieleusis** [comment] 2016-12-08 06:43
I am guessing that with null aware operators that method could be:

```dart
static LinkedList fromJson(Map json, aFromJson(Map json)) =>
      Nil.fromJson(json) ?? Cons.fromJson(json, aFromJson);
```

**Comment by polux** [comment] 2016-12-08 09:32
Using null-aware operators is a good idea! They didn't exist at the time.

You wrote "but also incorrect", what part is incorrect in the code above?

**Comment by alexeieleusis** [comment] 2016-12-08 16:19
It is incorrect in the sense that the analyzer cannot infer it will always return something.

**Comment by polux** [comment] 2016-12-09 08:51
Closing since that was apparently the only issue with strong mode. Feel free to reopen if you find another issue.

**Closed as completed by polux** 2016-12-09 08:51 UTC
